"""Build the target list from lncrawl's source index.

The index is generated by `scripts/index_gen.py` in the lightnovel-crawler repo and
holds every crawler with its base URLs — several hundred real sites, a good share of
them behind Cloudflare. That makes it a far better corpus than a handful of hosts
picked by hand, and it is the corpus this library actually has to work against.

    uv run poe live-targets

Writes livetest/targets.json. Point `LNCRAWL_SOURCES` at the index if the sibling
checkout is not where this expects it.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
from typing import Any, Dict, List

HERE = pathlib.Path(__file__).parent

DEFAULT_INDEX = HERE.parents[1] / "lncrawl" / "sources" / "_index.json"


def main() -> None:
    index = pathlib.Path(os.environ.get("LNCRAWL_SOURCES") or DEFAULT_INDEX)
    if not index.exists():
        print(
            f"source index not found at {index}\n"
            "Set LNCRAWL_SOURCES to lightnovel-crawler's sources/_index.json",
            file=sys.stderr,
        )
        raise SystemExit(1)

    data = json.loads(index.read_text())
    crawlers = data.get("crawlers") or {}

    # One entry per host. A crawler often lists several URLs for the same site, and
    # probing the same host repeatedly would both skew the counts and be rude.
    seen: set = set()
    out: List[Dict[str, Any]] = []
    for crawler in crawlers.values():
        for url in crawler.get("base_urls") or []:
            host = str(url).split("//")[-1].split("/")[0]
            if host in seen:
                continue
            seen.add(host)
            out.append(
                {
                    "url": str(url),
                    "file": crawler.get("file_path"),
                    "lang": crawler.get("language"),
                }
            )

    (HERE / "targets.json").write_text(json.dumps(out, indent=1))
    print(f"{len(out)} unique hosts from {len(crawlers)} crawlers -> livetest/targets.json")


if __name__ == "__main__":
    main()
