"""Build the target list from lncrawl's source index.

The index is generated by `scripts/index_gen.py` in the lightnovel-crawler repo and
holds every crawler with its base URLs — several hundred real sites, a good share of
them behind Cloudflare. That makes it a far better corpus than a handful of hosts
picked by hand, and it is the corpus this library actually has to work against.

    uv run poe live-targets

Fetched from the lightnovel-crawler repository rather than a sibling checkout, so this
works without one and everybody building the corpus builds the same corpus. Point
`LNCRAWL_SOURCES` at a local `_index.json` to use a working tree instead — the only
way to include sources that are not committed yet.

Writes livetest/targets.json.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
from typing import Any, Dict, List, Optional

import requests

HERE = pathlib.Path(__file__).parent

SOURCES_URL = "https://raw.githubusercontent.com/lncrawl/lightnovel-crawler/dev/sources"


def host_of(url: str) -> str:
    return str(url).split("//")[-1].split("/")[0].lower()


def load(name: str, local: Optional[pathlib.Path]) -> Dict[str, Any]:
    """One of lncrawl's source files, from a working tree or from GitHub."""
    if local is not None:
        path = local.parent / name
        if not path.exists():
            print(f"{path} not found", file=sys.stderr)
            raise SystemExit(1)
        return json.loads(path.read_text())

    response = requests.get(f"{SOURCES_URL}/{name}", timeout=60)
    response.raise_for_status()
    return response.json()


def rejected_hosts(data: Dict[str, Any]) -> Dict[str, str]:
    """Hosts lncrawl has disabled, as host -> reason.

    `sources/_rejected.json` is lncrawl's own record of sites that are gone — expired
    domains, dead projects, sites that stopped carrying novels. They must not be in
    the corpus: a host that cannot answer is not evidence about a client, and it
    drags every arm's rate toward whatever share of the list is dead.
    """
    return {host_of(url): str(reason) for url, reason in data.items()}


def main() -> None:
    override = os.environ.get("LNCRAWL_SOURCES")
    local = pathlib.Path(override) if override else None
    if local is not None and not local.exists():
        print(f"LNCRAWL_SOURCES points at {local}, which does not exist", file=sys.stderr)
        raise SystemExit(1)
    print(f"reading {local.parent if local else SOURCES_URL}")

    data = load("_index.json", local)
    crawlers = data.get("crawlers") or {}
    rejected = rejected_hosts(load("_rejected.json", local))

    # One entry per host. A crawler often lists several URLs for the same site, and
    # probing the same host repeatedly would both skew the counts and be rude.
    seen: set = set()
    skipped = 0
    out: List[Dict[str, Any]] = []
    for crawler in crawlers.values():
        for url in crawler.get("base_urls") or []:
            host = host_of(url)
            if host in seen:
                continue
            seen.add(host)
            if host in rejected:
                skipped += 1
                continue
            out.append(
                {
                    "url": str(url),
                    "file": crawler.get("file_path"),
                    "lang": crawler.get("language"),
                }
            )

    (HERE / "targets.json").write_text(json.dumps(out, indent=1))
    print(f"{len(out)} unique hosts from {len(crawlers)} crawlers -> livetest/targets.json")
    print(f"{skipped} skipped as rejected by lncrawl ({len(rejected)} on its list)")


if __name__ == "__main__":
    main()
